# 🛡️ Sketch Gate Configuration

# 네트워크 감시 포트
server.port=8080

# [Count-Min Sketch 세부 설정]
# cms.width: 해시 버킷 개수.
# 비트 연산 최적화(&) 및 CPU L2/L3 캐시 적중률 향상을 위해 2^16(65536)으로 설정
# CMS 메모리 사용량: (65536 * 4 바이트) * 4 = 약 1MB
# d=4인 경우, 오차율(ε)은 약 0.0044, 신뢰도(1-δ)는 약 99.56% 수준 보장
cms.width=65536

# cms.depth: 독립적 해시 함수 개수.
# 연산 비용(CPU)과 해시 충돌 오차율(정확도)의 최적 밸런스(수학적 효율성 검증 값)
# d=4인 경우, 연산 비용은 4배, 오차율은 1/4 수준
cms.depth=4

# 차단 임계치 (1초 동안 한 IP가 보낼 수 있는 최대 패킷 수)
packet.max.limit=100